### ISSUE TITLE
Danubia phpdf

### ISSUE THREAD

**Issue by tifannyknox** [php-df/quero-palestrar#1]
Título: **UX: O que é a Experiência do usuário?**  
Palavras-chaves: `UX`, `Design`, `Strategy`  
Nível: *Intermediário*  
Palestrante: [**Danubia Barreto Soares**] #3 
Descrição da palestra:
> Você já ouviu falar de User Experience? Se você nunca ouviu ou então tem aquela "noção" do que seja, ou até para os que manjam do assunto, na minha palestra vou falar um pouco como funciona a experiência do usuário, e como aplica-lá na sua empresa.
Antes de começar a desenvolver um site e um aplicativo, primeiramente pensamos na experiência que o usuário vai ter no nosso site, pois um site que ele ache "dificultoso" não vai atraí-lo, ele perderá a paciência e sairá do seu site. Então, como fazer algo realmente interessante para o usuário? Como manter uma estratégia para que o usuário se sinta confortável em ver? 
 

Slides: link para os slides publicado (opcional)  
Vídeo: link para o vídeo publicado (opcional)
GitHub: link para repositório do GitHub com exemplos (opcional)

**Comment by raniery** [comment]
@tifannyknox favor, abrir primeiro uma issue de cadastro de palestrante.

**Comment by leonnleite** [comment]
repetido, https://github.com/php-df/quero-palestrar/issues/3
